import type { CustomerCase } from '@/types';
import { subDays, subHours, addDays, addHours } from 'date-fns';

const now = new Date();

export const INITIAL_CASES: CustomerCase[] = [
  {
    id: 'CASE-001',
    caseNumber: 'CS-2026-0891',
    title: 'Unable to access trading account online',
    description: 'Customer reports being unable to log in to the online trading portal for 3 days. Password reset attempts have not resolved the issue. Customer needs urgent access as there is an active IPO subscription.',
    category: 'Technical Issue',
    priority: 'High',
    status: 'In Progress',
    customerId: 'IND-9021',
    customerName: 'Eleanor Vance',
    assignedTo: 'Dara Heng',
    assignedRole: 'CSO',
    branch: 'Phnom Penh Main Branch',
    createdAt: subDays(now, 2).toISOString(),
    updatedAt: subHours(now, 4).toISOString(),
    slaDeadline: addHours(subDays(now, 2), 24).toISOString(),
    slaBreached: true,
    activities: [
      {
        id: 'ACT-001a',
        type: 'created',
        description: 'Case created via phone call. Customer unable to access online trading portal.',
        performedBy: 'Dara Heng',
        timestamp: subDays(now, 2).toISOString(),
      },
      {
        id: 'ACT-001b',
        type: 'assigned',
        description: 'Case assigned to CSO team for technical resolution.',
        performedBy: 'Rattanak Pov',
        timestamp: subDays(now, 2).toISOString(),
        newStatus: 'Assigned',
      },
      {
        id: 'ACT-001c',
        type: 'status_change',
        description: 'Escalated to IT support team. Customer account appears locked at backend level.',
        performedBy: 'Dara Heng',
        timestamp: subDays(now, 1).toISOString(),
        newStatus: 'In Progress',
      },
      {
        id: 'ACT-001d',
        type: 'comment',
        description: 'IT team confirmed account was locked due to 5 failed login attempts. Unlock request submitted to system admin.',
        performedBy: 'Dara Heng',
        timestamp: subHours(now, 4).toISOString(),
      },
    ],
  },
  {
    id: 'CASE-002',
    caseNumber: 'CS-2026-0890',
    title: 'KYC document re-submission request',
    description: 'Customer was notified that their national ID submitted during registration was unclear/low quality scan. Customer needs guidance on how to re-submit a higher quality scan.',
    category: 'KYC / Document',
    priority: 'Medium',
    status: 'Pending',
    customerId: 'IND-9022',
    customerName: 'Marcus Chen',
    assignedTo: 'Sopheak Meas',
    assignedRole: 'SR',
    branch: 'Phnom Penh Main Branch',
    createdAt: subDays(now, 4).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
    slaDeadline: addDays(subDays(now, 4), 5).toISOString(),
    slaBreached: false,
    activities: [
      {
        id: 'ACT-002a',
        type: 'created',
        description: 'Case opened by KYC officer after reviewing uploaded documents.',
        performedBy: 'Sopheak Meas',
        timestamp: subDays(now, 4).toISOString(),
      },
      {
        id: 'ACT-002b',
        type: 'comment',
        description: 'Contacted customer via SMS with document quality requirements.',
        performedBy: 'Sopheak Meas',
        timestamp: subDays(now, 3).toISOString(),
      },
      {
        id: 'ACT-002c',
        type: 'status_change',
        description: 'Awaiting customer to re-submit higher quality document scan.',
        performedBy: 'Sopheak Meas',
        timestamp: subDays(now, 1).toISOString(),
        newStatus: 'Pending',
      },
    ],
  },
  {
    id: 'CASE-003',
    caseNumber: 'CS-2026-0885',
    title: 'IPO subscription amount not reflected in account',
    description: 'Customer subscribed to PPSP IPO for 5,000 shares ($2,500) on the last subscription day. Three days later the subscription is not visible in their account view. Customer is concerned about the subscription status.',
    category: 'IPO / Subscription',
    priority: 'Critical',
    status: 'Assigned',
    customerId: 'IND-9023',
    customerName: 'Isabelle Fontaine',
    assignedTo: 'Rattanak Pov',
    assignedRole: 'Manager',
    branch: 'Siem Reap Branch',
    createdAt: subDays(now, 3).toISOString(),
    updatedAt: subHours(now, 2).toISOString(),
    slaDeadline: addHours(subDays(now, 3), 8).toISOString(),
    slaBreached: true,
    activities: [
      {
        id: 'ACT-003a',
        type: 'created',
        description: 'Case escalated from front desk. IPO subscription not visible.',
        performedBy: 'Victoria Sterling',
        timestamp: subDays(now, 3).toISOString(),
      },
      {
        id: 'ACT-003b',
        type: 'assigned',
        description: 'Assigned to Operations Manager for urgent review.',
        performedBy: 'Rattanak Pov',
        timestamp: subDays(now, 3).toISOString(),
        newStatus: 'Assigned',
      },
      {
        id: 'ACT-003c',
        type: 'comment',
        description: 'Confirmed subscription batch file was received. Processing delay due to system maintenance. Expected to reflect in 24 hours.',
        performedBy: 'Rattanak Pov',
        timestamp: subHours(now, 2).toISOString(),
      },
    ],
  },
  {
    id: 'CASE-004',
    caseNumber: 'CS-2026-0879',
    title: 'Dividend not credited for PPSP holding',
    description: 'Customer claims dividend of KHR 1,250,000 for Q2 2026 has not been credited to their savings account. Customer has held PPSP shares for over 2 years.',
    category: 'Transaction Dispute',
    priority: 'High',
    status: 'Resolved',
    customerId: 'IND-9024',
    customerName: 'Rafael Montoya',
    assignedTo: 'Dara Heng',
    assignedRole: 'CSO',
    branch: 'Phnom Penh Main Branch',
    createdAt: subDays(now, 8).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
    resolvedAt: subDays(now, 1).toISOString(),
    slaDeadline: addDays(subDays(now, 8), 3).toISOString(),
    slaBreached: false,
    resolutionNotes: 'Confirmed with operations team that dividend was processed but routed to an incorrect account number on file. Corrected account number and dividend credited on 28 Sep 2026. Customer notified via SMS.',
    activities: [
      {
        id: 'ACT-004a',
        type: 'created',
        description: 'Customer complaint via branch visit.',
        performedBy: 'Dara Heng',
        timestamp: subDays(now, 8).toISOString(),
      },
      {
        id: 'ACT-004b',
        type: 'assigned',
        description: 'Assigned to back-office operations.',
        performedBy: 'Dara Heng',
        timestamp: subDays(now, 8).toISOString(),
        newStatus: 'Assigned',
      },
      {
        id: 'ACT-004c',
        type: 'comment',
        description: 'Found routing error — dividend was sent to old account number.',
        performedBy: 'Dara Heng',
        timestamp: subDays(now, 3).toISOString(),
      },
      {
        id: 'ACT-004d',
        type: 'resolved',
        description: 'Dividend corrected and credited. Customer confirmation obtained.',
        performedBy: 'Dara Heng',
        timestamp: subDays(now, 1).toISOString(),
        newStatus: 'Resolved',
      },
    ],
  },
  {
    id: 'CASE-005',
    caseNumber: 'CS-2026-0871',
    title: 'Request to update registered mobile number',
    description: 'Customer requests to change the mobile number linked to their trading account from +855 12 111 222 to +855 77 333 444. Customer has presented their National ID for verification.',
    category: 'Account Issue',
    priority: 'Low',
    status: 'Closed',
    customerId: 'IND-9025',
    customerName: 'Kosal Neang',
    assignedTo: 'Sopheak Meas',
    assignedRole: 'SR',
    branch: 'Kampong Cham Branch',
    createdAt: subDays(now, 12).toISOString(),
    updatedAt: subDays(now, 10).toISOString(),
    resolvedAt: subDays(now, 11).toISOString(),
    closedAt: subDays(now, 10).toISOString(),
    slaDeadline: addDays(subDays(now, 12), 2).toISOString(),
    slaBreached: false,
    resolutionNotes: 'Customer verification completed. Mobile number updated in system. Customer confirmed receipt of OTP on new number.',
    activities: [
      {
        id: 'ACT-005a',
        type: 'created',
        description: 'Walk-in customer request to update mobile number.',
        performedBy: 'Sopheak Meas',
        timestamp: subDays(now, 12).toISOString(),
      },
      {
        id: 'ACT-005b',
        type: 'status_change',
        description: 'Identity verified. Mobile number update submitted to system.',
        performedBy: 'Sopheak Meas',
        timestamp: subDays(now, 11).toISOString(),
        newStatus: 'In Progress',
      },
      {
        id: 'ACT-005c',
        type: 'resolved',
        description: 'Mobile number updated successfully. Customer sent test OTP.',
        performedBy: 'Sopheak Meas',
        timestamp: subDays(now, 11).toISOString(),
        newStatus: 'Resolved',
      },
      {
        id: 'ACT-005d',
        type: 'closed',
        description: 'Customer confirmed mobile number works. Case closed.',
        performedBy: 'Rattanak Pov',
        timestamp: subDays(now, 10).toISOString(),
        newStatus: 'Closed',
      },
    ],
  },
  {
    id: 'CASE-006',
    caseNumber: 'CS-2026-0892',
    title: 'Complaint: long wait time at Siem Reap branch',
    description: 'Customer filed a formal complaint about excessive wait time (over 45 minutes) at Siem Reap branch on 27 September 2026. Customer was there for a routine account query.',
    category: 'Complaint',
    priority: 'Medium',
    status: 'Open',
    customerId: 'IND-9026',
    customerName: 'Phearak Ung',
    branch: 'Siem Reap Branch',
    createdAt: subHours(now, 18).toISOString(),
    updatedAt: subHours(now, 18).toISOString(),
    slaDeadline: addDays(now, 2).toISOString(),
    slaBreached: false,
    activities: [
      {
        id: 'ACT-006a',
        type: 'created',
        description: 'Complaint received via email. Customer is requesting a formal response and compensation.',
        performedBy: 'System',
        timestamp: subHours(now, 18).toISOString(),
      },
    ],
  },
  {
    id: 'CASE-007',
    caseNumber: 'CS-2026-0888',
    title: 'Information request: margin trading eligibility',
    description: 'Customer enquires about eligibility for margin trading facility. Wants to understand the minimum portfolio value, documentation requirements, and interest rate terms.',
    category: 'Information Request',
    priority: 'Low',
    status: 'Assigned',
    customerId: 'IND-9027',
    customerName: 'Chanthea Ros',
    assignedTo: 'Victoria Sterling',
    assignedRole: 'SR',
    branch: 'Phnom Penh Main Branch',
    createdAt: subDays(now, 5).toISOString(),
    updatedAt: subDays(now, 4).toISOString(),
    slaDeadline: addDays(subDays(now, 5), 3).toISOString(),
    slaBreached: false,
    activities: [
      {
        id: 'ACT-007a',
        type: 'created',
        description: 'Customer information request via website contact form.',
        performedBy: 'System',
        timestamp: subDays(now, 5).toISOString(),
      },
      {
        id: 'ACT-007b',
        type: 'assigned',
        description: 'Assigned to SR for advisory response.',
        performedBy: 'Rattanak Pov',
        timestamp: subDays(now, 4).toISOString(),
        newStatus: 'Assigned',
      },
    ],
  },
];
