import { Individual, Customer360Profile } from '@/types';
import { GENERATED_INDIVIDUALS } from './seed-customers';

/** The eight hand-written seeds; generated customers are appended below. */
const BASE_INDIVIDUALS: Individual[] = [
  {
    id: 'IND-9021',
    customerId: 'CID-009021',
    firstName: 'Eleanor',
    lastName: 'Vance',
    surnameEN: 'Vance',
    givenNameEN: 'Eleanor',
    surnameKH: 'វ៉ានស៍',
    givenNameKH: 'អេលីន័រ',
    fullNameEN: 'Eleanor Vance',
    fullNameKH: 'អេលីន័រ វ៉ានស៍',
    email: 'eleanor.vance@vancetech.io',
    phone: '+855 12 892 340',
    mobile: '+855 12 892 340',
    telephone: '+855 23 998 101',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1988-04-14',
    gender: 'Female',
    maritalStatus: 'Married',
    nationality: 'Cambodian',

    // Investor Profile
    securitiesKnowledge: 'Advanced',
    riskCategory: 'Moderate',
    investmentExperience: '5+ years',
    customerType: 'High Net Worth',
    educationBackground: "Master's",

    // Identification
    residency: 'Resident',
    idType: 'National ID',
    idNumber: 'KHM-019829381',
    issuedBy: 'General Department of Identification',
    issuedDate: '2020-05-12',
    expiredDate: '2030-05-12',
    taxpayerIdNumber: 'TIN-889102941',
    supportingDocuments: [
      {
        id: 'DOC-01',
        type: 'Account Specimen',
        fileName: 'Signature_Specimen_Card.pdf',
        fileSize: '1.4 MB',
        uploadedAt: '2024-03-10',
        remark: 'Verified signature matches bank signature register.',
      },
      {
        id: 'DOC-02',
        type: 'ID Card / Passport',
        fileName: 'National_ID_Front_Back.pdf',
        fileSize: '2.8 MB',
        uploadedAt: '2024-03-10',
        remark: 'Biometrics matched with official registry.',
      },
      {
        id: 'DOC-03',
        type: 'Other',
        fileName: 'Proof_of_Address_Utility.pdf',
        fileSize: '890 KB',
        uploadedAt: '2024-03-11',
        remark: 'Electricity bill within 3 months.',
      },
    ],

    // Employment & Banking
    employment: {
      occupation: 'Managing Director & Founder',
      position: 'Executive Director',
      typeOfBusiness: 'Technology & Robotics',
      levelOfPosition: 'Executive / C-Level',
      organizationName: 'Vance Robotics Corp Ltd',
      lengthOfWork: '6 years',
      officeTelephone: '+855 23 881 990',
      organizationAddress: 'Exchange Square, Level 14, St 106, Phnom Penh',
    },
    banking: {
      bankName: 'Canadia Bank Plc',
      accountOwner: 'ELEANOR VANCE',
      savingAccount: 'Premier High-Yield Savings',
      accountNumber: '001 982 441 902',
    },

    // Family & Related Persons
    spouse: {
      fullName: 'Julian Vance',
      latin: 'Julian Vance',
      email: 'julian.vance@techinvest.kh',
      yearOfEmployment: '2017',
      relationship: 'Spouse',
      occupation: 'Principal Architect',
      position: 'Partner',
      typeOfBusiness: 'Urban Architecture',
      mobile: '+855 12 887 651',
      officeTelephone: '+855 23 772 101',
      address: 'Villa 14, Street 240, Daun Penh, Phnom Penh',
    },
    relatedPerson: {
      fullName: 'Sokha Vance',
      latin: 'Sokha Vance',
      email: 'sokha.vance@familylaw.kh',
      gender: 'Male',
      relationship: 'Brother',
      mobile: '+855 17 992 001',
      address: 'No 45, Norodom Blvd, Phnom Penh',
    },

    // Account Information
    investorIdInfo: {
      investorIdNumber: 'INV-882910',
      securitiesFirm: 'Nexus Securities Plc',
      customerReceivedBy: 'Sophea Keo (CSO)',
      applicationDate: '2024-03-15',
      dateSentToSECC: '2024-03-18',
      dateReceivedFromSECC: '2024-03-25',
      investorIdExpiredDate: '2034-03-25',
      customerStatus: 'VIP',
    },
    tradingAccountInfo: {
      tradingAccountNumber: 'TRD-770192',
      accountDate: '2024-03-28',
      accountCheckedBy: 'Dara Vong (SR)',
      accountApprovedBy: 'Vannak Lim (Manager)',
      email: 'eleanor.vance@vancetech.io',
      currentAssignedSR: 'Dara Vong (SR)',
      phoneNumber: '+855 12 892 340',
    },

    // Statuses & Workflow
    profileStatus: 'Incomplete',
    accountStatus: 'Not Opened',
    requestType: 'Registration',
    requestStatus: 'Rejected',
    currentWorkflowStage: 'Manager',
    authorizationHistory: [
      {
        id: 'AUTH-101',
        stage: 'Application Submitted',
        status: 'Submitted',
        dateTime: '29 Apr 2026, 09:15 AM',
        processedBy: 'Chea Vichea',
        role: 'CSO',
      },
      {
        id: 'AUTH-102',
        stage: 'SR Authorization',
        status: 'Rejected',
        dateTime: '01 May 2026, 02:30 PM',
        processedBy: 'Meas Sokha',
        role: 'SR',
        reason: 'ID card number does not match the submitted documents.',
      },
      {
        id: 'AUTH-103',
        stage: 'Manager Authorization',
        status: 'Queue',
        dateTime: 'Queue',
        processedBy: 'Ly Chanthy',
        role: 'Manager',
      },
    ],

    // Compatibility fields
    idExpiryDate: '2030-05-12',
    kycStatus: 'verified',
    riskRating: 'low',
    category: 'Private Banking',
    occupation: 'Managing Director & Founder',
    employer: 'Vance Robotics Corp Ltd',
    annualIncome: 485000,
    creditScore: 814,
    netWorth: 3450000,
    totalDeposits: 1240500,
    branch: 'Phnom Penh Central Financial (Branch 101)',
    address: {
      street: '450 Preah Monivong Blvd, Penthouse 3',
      city: 'Phnom Penh',
      state: 'Daun Penh',
      postalCode: '120201',
      country: 'Cambodia',
    },
    tags: ['Ultra High Net Worth', 'Tech Founder', 'Priority AML Approved'],
    createdAt: '2021-03-12',
    lastActive: '10 mins ago',
    relationshipManager: 'Victoria Sterling',
  },
  {
    id: 'IND-9022',
    customerId: 'CID-009022',
    firstName: 'Alexander',
    lastName: 'Wright',
    surnameEN: 'Wright',
    givenNameEN: 'Alexander',
    surnameKH: 'រ៉ាយ',
    givenNameKH: 'អាឡិចសាន់ឌ័រ',
    fullNameEN: 'Alexander Wright',
    fullNameKH: 'អាឡិចសាន់ឌ័រ រ៉ាយ',
    email: 'alex.wright@wrightcapital.co.uk',
    phone: '+855 11 946 083',
    mobile: '+855 11 946 083',
    telephone: '+855 23 991 223',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1982-11-29',
    gender: 'Male',
    maritalStatus: 'Single',
    nationality: 'British',

    // Investor Profile
    securitiesKnowledge: 'Professional',
    riskCategory: 'High',
    investmentExperience: '5+ years',
    customerType: 'High Net Worth',
    educationBackground: 'Doctorate',

    // Identification
    residency: 'Non-Resident',
    idType: 'Passport',
    idNumber: 'GBR-774019234',
    issuedBy: 'Her Majesty Passport Office',
    issuedDate: '2019-12-01',
    expiredDate: '2029-12-01',
    taxpayerIdNumber: 'TIN-GBR-9920192',
    supportingDocuments: [
      {
        id: 'DOC-11',
        type: 'Account Specimen',
        fileName: 'Specimen_Signature_AW.pdf',
        fileSize: '950 KB',
        uploadedAt: '2024-04-02',
        remark: 'Signature notarized by legal counsel.',
      },
      {
        id: 'DOC-12',
        type: 'ID Card / Passport',
        fileName: 'British_Passport_BioPage.pdf',
        fileSize: '3.1 MB',
        uploadedAt: '2024-04-02',
        remark: 'Apostille certification attached.',
      },
    ],

    // Employment & Banking
    employment: {
      occupation: 'Senior Quantitative Analyst',
      position: 'Head of Algorithmic Assets',
      typeOfBusiness: 'Asset Management',
      levelOfPosition: 'Senior',
      organizationName: 'Mayfair Asset Partners LLP',
      lengthOfWork: '7 years',
      officeTelephone: '+44 20 7946 0800',
      organizationAddress: '18 Berkeley Square, Mayfair, London',
    },
    banking: {
      bankName: 'Canadia Bank Plc',
      accountOwner: 'ALEXANDER WRIGHT',
      savingAccount: 'Foreign Currency Portfolio',
      accountNumber: '002 884 102 994',
    },

    investorIdInfo: {
      investorIdNumber: 'INV-773821',
      securitiesFirm: 'Nexus Securities Plc',
      customerReceivedBy: 'Vireak Meas (CSO)',
      applicationDate: '2024-04-05',
      dateSentToSECC: '2024-04-08',
      dateReceivedFromSECC: 'Pending',
      investorIdExpiredDate: '2034-04-05',
      customerStatus: 'VIP',
    },
    tradingAccountInfo: {
      tradingAccountNumber: 'TRD-882019',
      accountDate: '2024-04-10',
      accountCheckedBy: 'Dara Vong (SR)',
      accountApprovedBy: 'Pending Manager',
      email: 'alex.wright@wrightcapital.co.uk',
      currentAssignedSR: 'Dara Vong (SR)',
      phoneNumber: '+855 11 946 083',
    },

    // Statuses & Workflow
    profileStatus: 'Incomplete',
    accountStatus: 'Not Opened',
    requestType: 'Registration',
    requestStatus: 'Pending',
    currentWorkflowStage: 'SR',
    authorizationHistory: [
      {
        id: 'AUTH-201',
        stage: 'Application Submitted — CSO',
        status: 'Submitted',
        dateTime: '2024-04-05 10:15 AM',
        processedBy: 'Vireak Meas',
        role: 'CSO',
        comment: 'Non-resident cross-border application submitted. Awaiting SECC clearance.',
      },
      {
        id: 'AUTH-202',
        stage: 'SR Review',
        status: 'Pending',
        dateTime: '2024-04-06 03:00 PM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Under review by Senior Representative for overseas AML validation.',
      },
    ],

    idExpiryDate: '2029-12-01',
    kycStatus: 'pending',
    riskRating: 'low',
    category: 'Wealth & Premier',
    occupation: 'Senior Quantitative Analyst',
    employer: 'Mayfair Asset Partners',
    annualIncome: 360000,
    creditScore: 795,
    netWorth: 2180000,
    totalDeposits: 890000,
    branch: 'London Canary Wharf (Branch 022)',
    address: {
      street: '18 Berkeley Square',
      city: 'London',
      state: 'Greater London',
      postalCode: 'W1J 6DA',
      country: 'United Kingdom',
    },
    tags: ['Cross-Border FX', 'Algorithmic Trader', 'Gold Tier'],
    createdAt: '2022-07-19',
    lastActive: '25 mins ago',
    relationshipManager: 'Julian Thorne',
  },
  {
    id: 'IND-9023',
    customerId: 'CID-009023',
    firstName: 'Sophia',
    lastName: 'Chen',
    surnameEN: 'Chen',
    givenNameEN: 'Sophia',
    surnameKH: 'ឈាន',
    givenNameKH: 'សូហ្វីយ៉ា',
    fullNameEN: 'Sophia Chen',
    fullNameKH: 'សូហ្វីយ៉ា ឈាន',
    email: 'sophia.chen@biogenex.sg',
    phone: '+855 16 712 904',
    mobile: '+855 16 712 904',
    telephone: '+855 23 889 001',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1993-02-18',
    gender: 'Female',
    maritalStatus: 'Single',
    nationality: 'Singaporean',

    // Investor Profile
    securitiesKnowledge: 'Intermediate',
    riskCategory: 'Moderate',
    investmentExperience: '3 - 5 years',
    customerType: 'Retail',
    educationBackground: 'Doctorate',

    // Identification
    residency: 'Resident',
    idType: 'National ID',
    idNumber: 'S-9348120A',
    issuedBy: 'Immigration & Checkpoints Authority',
    issuedDate: '2021-05-20',
    expiredDate: '2033-05-20',
    taxpayerIdNumber: 'TIN-SG-992011',
    supportingDocuments: [
      {
        id: 'DOC-21',
        type: 'Account Specimen',
        fileName: 'Specimen_Card_Sophia.pdf',
        fileSize: '1.1 MB',
        uploadedAt: '2024-05-01',
        remark: 'Specimen card verified.',
      },
      {
        id: 'DOC-22',
        type: 'ID Card / Passport',
        fileName: 'Singapore_NRIC_Card.pdf',
        fileSize: '2.4 MB',
        uploadedAt: '2024-05-01',
        remark: 'Employment pass verified.',
      },
    ],

    // Employment & Banking
    employment: {
      occupation: 'Chief Medical Officer',
      position: 'VP Clinical Research',
      typeOfBusiness: 'Biotechnology & Health',
      levelOfPosition: 'Executive / C-Level',
      organizationName: 'BioGenex Therapeutics',
      lengthOfWork: '5 years',
      officeTelephone: '+65 6712 9000',
      organizationAddress: '12 Marina Boulevard, Tower 3, Singapore',
    },
    banking: {
      bankName: 'Canadia Bank Plc',
      accountOwner: 'SOPHIA CHEN',
      savingAccount: 'Direct Equity Trading Deposit',
      accountNumber: '001 773 992 110',
    },

    investorIdInfo: {
      investorIdNumber: 'INV-662910',
      securitiesFirm: 'Nexus Securities Plc',
      customerReceivedBy: 'Sophea Keo (CSO)',
      applicationDate: '2024-05-01',
      dateSentToSECC: '2024-05-03',
      dateReceivedFromSECC: '2024-05-09',
      investorIdExpiredDate: '2034-05-09',
      customerStatus: 'Normal',
    },
    tradingAccountInfo: {
      tradingAccountNumber: 'TRD-991823',
      accountDate: '2024-05-12',
      accountCheckedBy: 'Dara Vong (SR)',
      accountApprovedBy: 'Pending Manager',
      email: 'sophia.chen@biogenex.sg',
      currentAssignedSR: 'Dara Vong (SR)',
      phoneNumber: '+855 16 712 904',
    },

    // Statuses & Workflow
    profileStatus: 'Incomplete',
    accountStatus: 'Not Opened',
    requestType: 'Registration',
    requestStatus: 'Resubmit',
    currentWorkflowStage: 'Resubmit',
    authorizationHistory: [
      {
        id: 'AUTH-301',
        stage: 'Application Submitted — CSO',
        status: 'Submitted',
        dateTime: '2024-05-01 09:00 AM',
        processedBy: 'Sophea Keo',
        role: 'CSO',
        comment: 'Submitted application for Singapore resident.',
      },
      {
        id: 'AUTH-302',
        stage: 'SR Review',
        status: 'Resubmit',
        dateTime: '2024-05-02 04:30 PM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Tax identification document copy is blurred and signature page is cut off.',
        reason: 'Please upload a clear scanned color copy of Taxpayer ID TIN document and complete signature specimen.',
      },
    ],

    idExpiryDate: '2033-05-20',
    kycStatus: 'under_review',
    riskRating: 'low',
    category: 'Wealth & Premier',
    occupation: 'Chief Medical Officer',
    employer: 'BioGenex Therapeutics',
    annualIncome: 290000,
    creditScore: 782,
    netWorth: 1750000,
    totalDeposits: 640000,
    branch: 'Singapore Marina Bay (Branch 055)',
    address: {
      street: '12 Marina Boulevard, Tower 3',
      city: 'Singapore',
      state: 'Central',
      postalCode: '018982',
      country: 'Singapore',
    },
    tags: ['Biotech Executive', 'ESG Portfolio', 'Cross-Border Asia'],
    createdAt: '2023-01-14',
    lastActive: '1 hour ago',
    relationshipManager: 'Victoria Sterling',
  },
  {
    id: 'IND-9024',
    customerId: 'CID-009024',
    firstName: 'Marcus',
    lastName: 'Brody',
    surnameEN: 'Brody',
    givenNameEN: 'Marcus',
    surnameKH: 'ប្រូឌី',
    givenNameKH: 'ម៉ាកឺស',
    fullNameEN: 'Marcus Brody',
    fullNameKH: 'ម៉ាកឺស ប្រូឌី',
    email: 'm.brody@brody-logistics.de',
    phone: '+855 12 334 556',
    mobile: '+855 12 334 556',
    telephone: '+855 23 881 223',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1976-09-03',
    gender: 'Male',
    maritalStatus: 'Married',
    nationality: 'German',

    // Investor Profile
    securitiesKnowledge: 'Intermediate',
    riskCategory: 'Low',
    investmentExperience: '5+ years',
    customerType: 'Corporate Officer',
    educationBackground: "Bachelor's",

    // Identification
    residency: 'Resident',
    idType: 'National ID',
    idNumber: 'DEU-109284771',
    issuedBy: 'Bundesrepublik Deutschland',
    issuedDate: '2018-09-03',
    expiredDate: '2028-09-03',
    taxpayerIdNumber: 'TIN-DEU-449102',
    supportingDocuments: [
      {
        id: 'DOC-31',
        type: 'Account Specimen',
        fileName: 'Marcus_Specimen_2024.pdf',
        fileSize: '1.2 MB',
        uploadedAt: '2024-01-10',
        remark: 'Official seal stamped.',
      },
      {
        id: 'DOC-32',
        type: 'ID Card / Passport',
        fileName: 'German_ID_Card.pdf',
        fileSize: '2.1 MB',
        uploadedAt: '2024-01-10',
        remark: 'Valid National ID.',
      },
    ],

    // Employment & Banking
    employment: {
      occupation: 'Chief Supply Officer',
      position: 'Managing Director',
      typeOfBusiness: 'Freight & Logistics',
      levelOfPosition: 'Executive / C-Level',
      organizationName: 'EuroLogistics Trans GmbH',
      lengthOfWork: '12 years',
      officeTelephone: '+49 30 5543 9900',
      organizationAddress: 'Kaiserstraße 44, Frankfurt',
    },
    banking: {
      bankName: 'Canadia Bank Plc',
      accountOwner: 'MARCUS BRODY',
      savingAccount: 'Corporate Executive Savings',
      accountNumber: '003 449 102 881',
    },

    investorIdInfo: {
      investorIdNumber: 'INV-449102',
      securitiesFirm: 'Nexus Securities Plc',
      customerReceivedBy: 'Vireak Meas (CSO)',
      applicationDate: '2024-01-10',
      dateSentToSECC: '2024-01-12',
      dateReceivedFromSECC: '2024-01-20',
      investorIdExpiredDate: '2034-01-20',
      customerStatus: 'VIP',
    },
    tradingAccountInfo: {
      tradingAccountNumber: 'TRD-330192',
      accountDate: '2024-01-22',
      accountCheckedBy: 'Dara Vong (SR)',
      accountApprovedBy: 'Vannak Lim (Manager)',
      email: 'm.brody@brody-logistics.de',
      currentAssignedSR: 'Dara Vong (SR)',
      phoneNumber: '+855 12 334 556',
    },

    // Statuses & Workflow
    profileStatus: 'Completed',
    accountStatus: 'Active',
    requestType: 'Close Account',
    requestStatus: 'Pending',
    currentWorkflowStage: 'Manager',
    closeAccountInfo: {
      closeDate: '2024-06-01',
      account: 'Trading Account TRD-330192',
      reason: 'Customer relocated corporate treasury and requested account closure.',
    },
    authorizationHistory: [
      {
        id: 'AUTH-398',
        requestType: 'Registration',
        stage: 'Application Submitted — CSO',
        status: 'Submitted',
        dateTime: '2024-01-10 09:15 AM',
        processedBy: 'Vireak Meas',
        role: 'CSO',
        comment: 'Initial customer onboarding application submitted with verified German National ID.',
      },
      {
        id: 'AUTH-399',
        requestType: 'Registration',
        stage: 'SR Authorization',
        status: 'Approved',
        dateTime: '2024-01-15 02:20 PM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Investor documents, AML and PEP screening checks verified and approved.',
      },
      {
        id: 'AUTH-400',
        requestType: 'Registration',
        stage: 'Manager Final Authorization',
        status: 'Approved',
        dateTime: '2024-01-22 04:00 PM',
        processedBy: 'Vannak Lim',
        role: 'Manager',
        comment: 'Final authorization approved. Trading Account TRD-330192 opened successfully.',
      },
      {
        id: 'AUTH-401',
        requestType: 'Close Account',
        stage: 'Close Account Request — CSO',
        status: 'Submitted',
        dateTime: '2024-06-01 10:00 AM',
        processedBy: 'Sophea Keo',
        role: 'CSO',
        comment: 'Customer requested account closure following full portfolio liquidation.',
        reason: 'Relocating assets to Europe central office.',
      },
      {
        id: 'AUTH-402',
        requestType: 'Close Account',
        stage: 'SR Review',
        status: 'Pending',
        dateTime: '2024-06-01 02:30 PM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Verified open position balance is zero and all settlement fees paid.',
      },
      {
        id: 'AUTH-403',
        requestType: 'Close Account',
        stage: 'SR Authorization',
        status: 'Approved',
        dateTime: '2024-06-02 11:00 AM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'SR authorization granted for closure. Sent to Manager for final authorization.',
      },
      {
        id: 'AUTH-404',
        requestType: 'Close Account',
        stage: 'Manager Review',
        status: 'Pending',
        dateTime: '2024-06-02 03:15 PM',
        processedBy: 'Vannak Lim',
        role: 'Manager',
        comment: 'Pending Manager final closure sign-off.',
      },
    ],

    idExpiryDate: '2028-09-03',
    kycStatus: 'under_review',
    riskRating: 'moderate',
    category: 'Corporate Officer',
    occupation: 'Chief Supply Officer',
    employer: 'EuroLogistics Trans GmbH',
    annualIncome: 215000,
    creditScore: 742,
    netWorth: 980000,
    totalDeposits: 310000,
    branch: 'Frankfurt Taunusanlage (Branch 008)',
    address: {
      street: 'Kaiserstraße 44',
      city: 'Frankfurt',
      state: 'Hessen',
      postalCode: '60329',
      country: 'Germany',
    },
    tags: ['Cross-Border Freight', 'PEP Check Pending', 'Audit Flag'],
    createdAt: '2023-08-20',
    lastActive: '3 hours ago',
    relationshipManager: 'Helena Weber',
  },
  {
    id: 'IND-9025',
    customerId: 'CID-009025',
    firstName: 'Clara',
    lastName: 'Moreau',
    surnameEN: 'Moreau',
    givenNameEN: 'Clara',
    surnameKH: 'ម៉ូរ៉ូ',
    givenNameKH: 'ក្លារ៉ា',
    fullNameEN: 'Clara Moreau',
    fullNameKH: 'ក្លារ៉ា ម៉ូរ៉ូ',
    email: 'c.moreau@atelier-paris.fr',
    phone: '+855 12 778 990',
    mobile: '+855 12 778 990',
    telephone: '+855 23 720 119',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1990-07-22',
    gender: 'Female',
    maritalStatus: 'Married',
    nationality: 'French',

    // Investor Profile
    securitiesKnowledge: 'Intermediate',
    riskCategory: 'Moderate',
    investmentExperience: '3 - 5 years',
    customerType: 'Retail',
    educationBackground: "Bachelor's",

    // Identification
    residency: 'Resident',
    idType: 'Passport',
    idNumber: 'FRA-993810293',
    issuedBy: 'Préfecture de Police de Paris',
    issuedDate: '2021-10-18',
    expiredDate: '2031-10-18',
    taxpayerIdNumber: 'TIN-FRA-778901',
    supportingDocuments: [
      {
        id: 'DOC-41',
        type: 'Account Specimen',
        fileName: 'Specimen_Clara_Moreau.pdf',
        fileSize: '1.3 MB',
        uploadedAt: '2024-05-18',
        remark: 'Specimen submitted.',
      },
    ],

    // Employment & Banking
    employment: {
      occupation: 'Creative Director',
      position: 'Managing Partner',
      typeOfBusiness: 'Design & Luxury',
      levelOfPosition: 'Executive / C-Level',
      organizationName: 'Studio Lumière Paris',
      lengthOfWork: '6 years',
      officeTelephone: '+33 1 42 68 55 00',
      organizationAddress: '28 Rue du Faubourg Saint-Honoré, Paris',
    },
    banking: {
      bankName: 'Canadia Bank Plc',
      accountOwner: 'CLARA MOREAU',
      savingAccount: 'Standard Individual Savings',
      accountNumber: '001 882 109 443',
    },

    investorIdInfo: {
      investorIdNumber: 'INV-339102',
      securitiesFirm: 'Nexus Securities Plc',
      customerReceivedBy: 'Vireak Meas (CSO)',
      applicationDate: '2024-05-18',
      dateSentToSECC: '2024-05-20',
      dateReceivedFromSECC: 'Pending',
      investorIdExpiredDate: '2034-05-20',
      customerStatus: 'Normal',
    },
    tradingAccountInfo: {
      tradingAccountNumber: 'TRD-551029',
      accountDate: '2024-05-22',
      accountCheckedBy: 'Dara Vong (SR)',
      accountApprovedBy: 'Pending',
      email: 'c.moreau@atelier-paris.fr',
      currentAssignedSR: 'Dara Vong (SR)',
      phoneNumber: '+855 12 778 990',
    },

    // Statuses & Workflow
    profileStatus: 'Incomplete',
    accountStatus: 'Not Opened',
    requestType: 'Registration',
    requestStatus: 'Rejected',
    currentWorkflowStage: 'Rejected',
    authorizationHistory: [
      {
        id: 'AUTH-501',
        stage: 'Application Submitted — CSO',
        status: 'Submitted',
        dateTime: '2024-05-18 11:30 AM',
        processedBy: 'Vireak Meas',
        role: 'CSO',
        comment: 'Registration application submitted with initial papers.',
      },
      {
        id: 'AUTH-502',
        stage: 'SR Review',
        status: 'Rejected',
        dateTime: '2024-05-19 02:00 PM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Applicant residency certificate does not match tax declaration jurisdiction.',
        reason: 'Discrepancy in tax residence declaration versus provided French utility documentation.',
      },
    ],

    idExpiryDate: '2031-10-18',
    kycStatus: 'verified',
    riskRating: 'low',
    category: 'Retail',
    occupation: 'Creative Director',
    employer: 'Studio Lumière',
    annualIncome: 145000,
    creditScore: 760,
    netWorth: 540000,
    totalDeposits: 185000,
    branch: 'Paris Boulevard Haussmann (Branch 014)',
    address: {
      street: '28 Rue du Faubourg Saint-Honoré',
      city: 'Paris',
      state: 'Île-de-France',
      postalCode: '75008',
      country: 'France',
    },
    tags: ['Luxury Retail', 'Verified ID', 'Instant SEPA'],
    createdAt: '2024-02-05',
    lastActive: '5 hours ago',
    relationshipManager: 'Antoine Laurent',
  },
  {
    id: 'IND-9026',
    customerId: 'CID-009026',
    firstName: 'Kenji',
    lastName: 'Takahashi',
    surnameEN: 'Takahashi',
    givenNameEN: 'Kenji',
    surnameKH: 'តាកាហាស៊ី',
    givenNameKH: 'កេនជី',
    fullNameEN: 'Kenji Takahashi',
    fullNameKH: 'កេនជី តាកាហាស៊ី',
    email: 'kenji.takahashi@neo-tokyo.jp',
    phone: '+81 3 5555 0192',
    mobile: '+81 3 5555 0192',
    telephone: '+81 3 5555 0100',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1985-05-12',
    gender: 'Male',
    maritalStatus: 'Married',
    nationality: 'Japanese',

    // Investor Profile
    securitiesKnowledge: 'Advanced',
    riskCategory: 'Moderate',
    investmentExperience: '5+ years',
    customerType: 'High Net Worth',
    educationBackground: "Master's",

    // Identification
    residency: 'Non-Resident',
    idType: 'Passport',
    idNumber: 'JPN-448192049',
    issuedBy: 'Ministry of Foreign Affairs of Japan',
    issuedDate: '2022-03-30',
    expiredDate: '2032-03-30',
    taxpayerIdNumber: 'TIN-JPN-889021',
    supportingDocuments: [
      {
        id: 'DOC-51',
        type: 'Account Specimen',
        fileName: 'Japanese_Consular_Specimen.pdf',
        fileSize: '1.7 MB',
        uploadedAt: '2024-06-11',
        remark: 'Consular certification verified.',
      },
    ],

    // Employment & Banking
    employment: {
      occupation: 'VP of Engineering',
      position: 'Executive Director',
      typeOfBusiness: 'Aerospace & Robotics',
      levelOfPosition: 'Executive / C-Level',
      organizationName: 'AeroSpace Next Ltd',
      lengthOfWork: '9 years',
      officeTelephone: '+81 3 5555 0100',
      organizationAddress: '1-5-1 Marunouchi, Chiyoda-ku, Tokyo',
    },
    banking: {
      bankName: 'Canadia Bank Plc',
      accountOwner: 'KENJI TAKAHASHI',
      savingAccount: 'Foreign Investor JPY Account',
      accountNumber: '001 992 001 382',
    },

    investorIdInfo: {
      investorIdNumber: 'INV-992019',
      securitiesFirm: 'Nexus Securities Plc',
      customerReceivedBy: 'Sophea Keo (CSO)',
      applicationDate: '2024-06-11',
      dateSentToSECC: '2024-06-13',
      dateReceivedFromSECC: '2024-06-20',
      investorIdExpiredDate: '2034-06-20',
      customerStatus: 'VIP',
    },
    tradingAccountInfo: {
      tradingAccountNumber: 'TRD-778901',
      accountDate: '2024-06-22',
      accountCheckedBy: 'Dara Vong (SR)',
      accountApprovedBy: 'Vannak Lim (Manager)',
      email: 'kenji.takahashi@neo-tokyo.jp',
      currentAssignedSR: 'Dara Vong (SR)',
      phoneNumber: '+81 3 5555 0192',
    },

    // Statuses & Workflow
    profileStatus: 'Completed',
    accountStatus: 'Active',
    requestType: 'Registration',
    requestStatus: 'Approved',
    currentWorkflowStage: 'Approved',
    authorizationHistory: [
      {
        id: 'AUTH-601',
        stage: 'Application Submitted — CSO',
        status: 'Submitted',
        dateTime: '2024-06-11 09:30 AM',
        processedBy: 'Sophea Keo',
        role: 'CSO',
        comment: 'Application submitted for non-resident Japanese investor.',
      },
      {
        id: 'AUTH-602',
        stage: 'SR Review',
        status: 'Pending',
        dateTime: '2024-06-12 11:00 AM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Foreign passport and address proof verified.',
      },
      {
        id: 'AUTH-603',
        stage: 'SR Authorization',
        status: 'Approved',
        dateTime: '2024-06-12 03:00 PM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Authorized. Forwarded to Manager.',
      },
      {
        id: 'AUTH-604',
        stage: 'Manager Final Authorization',
        status: 'Approved',
        dateTime: '2024-06-13 04:30 PM',
        processedBy: 'Vannak Lim',
        role: 'Manager',
        comment: 'Approved. Trading account generated.',
      },
    ],

    idExpiryDate: '2032-03-30',
    kycStatus: 'pending',
    riskRating: 'moderate',
    category: 'Corporate Officer',
    occupation: 'VP of Engineering',
    employer: 'AeroSpace Next Ltd',
    annualIncome: 275000,
    creditScore: 768,
    netWorth: 1420000,
    totalDeposits: 510000,
    branch: 'Tokyo Marunouchi (Branch 091)',
    address: {
      street: '1-5-1 Marunouchi, Chiyoda-ku',
      city: 'Tokyo',
      state: 'Tokyo',
      postalCode: '100-0005',
      country: 'Japan',
    },
    tags: ['Aerospace', 'Pending Proof of Address', 'JPY / USD'],
    createdAt: '2024-06-11',
    lastActive: 'Yesterday',
    relationshipManager: 'Kenichi Sato',
  },
  {
    id: 'IND-9027',
    customerId: 'CID-009027',
    firstName: 'Amara',
    lastName: 'Okafor',
    surnameEN: 'Okafor',
    givenNameEN: 'Amara',
    surnameKH: 'អូកាហ្វ័រ',
    givenNameKH: 'អាម៉ារ៉ា',
    fullNameEN: 'Amara Okafor',
    fullNameKH: 'អាម៉ារ៉ា អូកាហ្វ័រ',
    email: 'amara.okafor@lagosfin.ng',
    phone: '+234 802 331 9980',
    mobile: '+234 802 331 9980',
    telephone: '+234 802 331 9900',
    avatarUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1991-12-04',
    gender: 'Female',
    maritalStatus: 'Single',
    nationality: 'Nigerian',

    // Investor Profile
    securitiesKnowledge: 'Intermediate',
    riskCategory: 'Moderate',
    investmentExperience: '3 - 5 years',
    customerType: 'Retail',
    educationBackground: "Bachelor's",

    // Identification
    residency: 'Non-Resident',
    idType: 'Passport',
    idNumber: 'NGA-552190842',
    issuedBy: 'Nigeria Immigration Service',
    issuedDate: '2019-01-14',
    expiredDate: '2029-01-14',
    taxpayerIdNumber: 'TIN-NGA-991823',
    supportingDocuments: [
      {
        id: 'DOC-61',
        type: 'Account Specimen',
        fileName: 'Specimen_Amara.pdf',
        fileSize: '890 KB',
        uploadedAt: '2023-11-18',
        remark: 'Specimen valid.',
      },
    ],

    // Employment & Banking
    employment: {
      occupation: 'Fintech Product Lead',
      position: 'VP Payments',
      typeOfBusiness: 'Financial Technology',
      levelOfPosition: 'Senior',
      organizationName: 'PayStack Africa',
      lengthOfWork: '4 years',
      officeTelephone: '+234 1 889 001',
      organizationAddress: '40 Bank Street, Canary Wharf, London',
    },
    banking: {
      bankName: 'Canadia Bank Plc',
      accountOwner: 'AMARA OKAFOR',
      savingAccount: 'Foreign Currency Account',
      accountNumber: '002 991 229 001',
    },

    investorIdInfo: {
      investorIdNumber: 'INV-118290',
      securitiesFirm: 'Nexus Securities Plc',
      customerReceivedBy: 'Vireak Meas (CSO)',
      applicationDate: '2023-11-18',
      dateSentToSECC: '2023-11-20',
      dateReceivedFromSECC: '2023-11-28',
      investorIdExpiredDate: '2033-11-28',
      customerStatus: 'Normal',
    },
    tradingAccountInfo: {
      tradingAccountNumber: 'TRD-440192',
      accountDate: '2023-12-01',
      accountCheckedBy: 'Dara Vong (SR)',
      accountApprovedBy: 'Vannak Lim (Manager)',
      email: 'amara.okafor@lagosfin.ng',
      currentAssignedSR: 'Dara Vong (SR)',
      phoneNumber: '+234 802 331 9980',
    },

    // Statuses & Workflow
    profileStatus: 'Completed',
    accountStatus: 'Active',
    requestType: 'Registration',
    requestStatus: 'Approved',
    currentWorkflowStage: 'Approved',
    authorizationHistory: [
      {
        id: 'AUTH-701',
        stage: 'Application Submitted — CSO',
        status: 'Submitted',
        dateTime: '2023-11-18 10:00 AM',
        processedBy: 'Vireak Meas',
        role: 'CSO',
        comment: 'Application submitted for international technology consultant.',
      },
      {
        id: 'AUTH-702',
        stage: 'SR Authorization',
        status: 'Approved',
        dateTime: '2023-11-19 02:30 PM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Verified and authorized.',
      },
      {
        id: 'AUTH-703',
        stage: 'Manager Final Authorization',
        status: 'Approved',
        dateTime: '2023-11-20 04:00 PM',
        processedBy: 'Vannak Lim',
        role: 'Manager',
        comment: 'Final approval recorded.',
      },
    ],

    idExpiryDate: '2029-01-14',
    kycStatus: 'verified',
    riskRating: 'low',
    category: 'Wealth & Premier',
    occupation: 'Fintech Product Lead',
    employer: 'PayStack Africa',
    annualIncome: 195000,
    creditScore: 775,
    netWorth: 820000,
    totalDeposits: 395000,
    branch: 'London Canary Wharf (Branch 022)',
    address: {
      street: '40 Bank Street, Canary Wharf',
      city: 'London',
      state: 'Greater London',
      postalCode: 'E14 5NR',
      country: 'United Kingdom',
    },
    tags: ['Fintech Leader', 'Diaspora Remittance', 'Fast Track KYC'],
    createdAt: '2023-11-18',
    lastActive: '40 mins ago',
    relationshipManager: 'Victoria Sterling',
  },
  {
    id: 'IND-9028',
    customerId: 'CID-009028',
    firstName: 'Mateo',
    lastName: 'Silva',
    surnameEN: 'Silva',
    givenNameEN: 'Mateo',
    surnameKH: 'ស៊ីលវ៉ា',
    givenNameKH: 'ម៉ាតេអូ',
    fullNameEN: 'Mateo Silva',
    fullNameKH: 'ម៉ាតេអូ ស៊ីលវ៉ា',
    email: 'mateo.silva@andesmin.cl',
    phone: '+56 2 2911 4400',
    mobile: '+56 2 2911 4400',
    telephone: '+56 2 2911 4400',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    dateOfBirth: '1979-08-16',
    gender: 'Male',
    maritalStatus: 'Divorced',
    nationality: 'Chilean',

    // Investor Profile
    securitiesKnowledge: 'Beginner',
    riskCategory: 'High',
    investmentExperience: '< 1 year',
    customerType: 'Retail',
    educationBackground: 'High School',

    // Identification
    residency: 'Non-Resident',
    idType: 'Driver License',
    idNumber: 'CHL-14892019-K',
    issuedBy: 'Servicio de Registro Civil e Identificacion',
    issuedDate: '2017-08-16',
    expiredDate: '2027-08-16',
    taxpayerIdNumber: 'TIN-CHL-119201',
    supportingDocuments: [
      {
        id: 'DOC-81',
        type: 'ID Card / Passport',
        fileName: 'Chile_Driver_License_Scan.pdf',
        fileSize: '1.2 MB',
        uploadedAt: '2024-04-10',
        remark: 'Expired identification presented.',
      },
    ],

    // Employment & Banking
    employment: {
      occupation: 'Commercial Broker',
      position: 'Broker',
      typeOfBusiness: 'Independent Brokerage',
      levelOfPosition: 'Staff',
      organizationName: 'Independent Brokerage',
      lengthOfWork: '2 years',
      officeTelephone: '+56 2 2911 4400',
      organizationAddress: '1200 Brickell Avenue, Suite 14, Miami',
    },
    banking: {
      bankName: 'Canadia Bank Plc',
      accountOwner: 'MATEO SILVA',
      savingAccount: 'Basic Retail Account',
      accountNumber: '001 440 910 882',
    },

    investorIdInfo: {
      investorIdNumber: 'INV-001928',
      securitiesFirm: 'Nexus Securities Plc',
      customerReceivedBy: 'Vireak Meas (CSO)',
      applicationDate: '2024-04-10',
      dateSentToSECC: 'Rejected before SECC',
      dateReceivedFromSECC: 'N/A',
      investorIdExpiredDate: 'N/A',
      customerStatus: 'Restricted',
    },
    tradingAccountInfo: {
      tradingAccountNumber: 'None',
      accountDate: 'N/A',
      accountCheckedBy: 'Dara Vong (SR)',
      accountApprovedBy: 'Rejected',
      email: 'mateo.silva@andesmin.cl',
      currentAssignedSR: 'Dara Vong (SR)',
      phoneNumber: '+56 2 2911 4400',
    },

    // Statuses & Workflow
    profileStatus: 'Incomplete',
    accountStatus: 'Not Opened',
    requestType: 'Registration',
    requestStatus: 'Rejected',
    currentWorkflowStage: 'Rejected',
    authorizationHistory: [
      {
        id: 'AUTH-801',
        stage: 'Application Submitted — CSO',
        status: 'Submitted',
        dateTime: '2024-04-10 08:30 AM',
        processedBy: 'Vireak Meas',
        role: 'CSO',
        comment: 'Application submitted with foreign driver license.',
      },
      {
        id: 'AUTH-802',
        stage: 'SR Review',
        status: 'Rejected',
        dateTime: '2024-04-10 11:45 AM',
        processedBy: 'Dara Vong',
        role: 'SR',
        comment: 'Driver license is not an acceptable primary ID for non-resident securities trading.',
        reason: 'SECC regulations mandate a valid certified International Passport for non-resident investors.',
      },
    ],

    idExpiryDate: '2027-08-16',
    kycStatus: 'rejected',
    riskRating: 'high',
    category: 'Retail',
    occupation: 'Commercial Broker',
    employer: 'Independent Brokerage',
    annualIncome: 110000,
    creditScore: 612,
    netWorth: 240000,
    totalDeposits: 45000,
    branch: 'Miami Brickell Financial (Branch 089)',
    address: {
      street: '1200 Brickell Avenue, Suite 14',
      city: 'Miami',
      state: 'FL',
      postalCode: '33131',
      country: 'United States',
    },
    tags: ['Sanction Flagged', 'Expired Documentation', 'High Risk KYC'],
    createdAt: '2024-04-10',
    lastActive: '3 days ago',
    relationshipManager: 'Gabriel Ross',
  }
];

export const INITIAL_INDIVIDUALS: Individual[] = [...BASE_INDIVIDUALS, ...GENERATED_INDIVIDUALS];

export const MOCK_CUSTOMER_360_DATA: Record<string, Omit<Customer360Profile, 'individual'>> = {
  'IND-9021': {
    relationshipScore: 96,
    churnRisk: 'Low',
    lifetimeValue: 142000,
    tenureYears: 5.4,
    accounts: [
      {
        id: 'ACC-801-9921',
        accountNumber: '•••• 9921',
        type: 'Checking',
        balance: 245000,
        currency: 'USD',
        status: 'Active',
      },
      {
        id: 'ACC-801-4402',
        accountNumber: '•••• 4402',
        type: 'High-Yield Savings',
        balance: 625500,
        currency: 'USD',
        status: 'Active',
        interestRate: '4.85% APY',
      },
      {
        id: 'ACC-801-1189',
        accountNumber: '•••• 1189',
        type: 'Investment Portfolio',
        balance: 370000,
        currency: 'USD',
        status: 'Active',
      }
    ],
    cards: [
      {
        id: 'CRD-101',
        cardNumber: '•••• •••• •••• 8841',
        type: 'Visa Infinite',
        cardHolder: 'ELEANOR VANCE',
        expiry: '09/29',
        limit: 100000,
        spent: 14320,
        status: 'Active',
        colorGradient: 'from-slate-900 via-blue-900 to-indigo-950',
      },
      {
        id: 'CRD-102',
        cardNumber: '•••• •••• •••• 3029',
        type: 'Virtual Fleet',
        cardHolder: 'VANCE ROBOTICS CORP',
        expiry: '12/27',
        limit: 50000,
        spent: 6800,
        status: 'Active',
        colorGradient: 'from-blue-500 via-cyan-600 to-teal-500',
      }
    ],
    transactions: [
      {
        id: 'TXN-901',
        date: 'Today, 14:22',
        description: 'Vance Robotics Corp Dividend Distribution',
        merchant: 'Vance Robotics Corp',
        category: 'Dividend',
        amount: 85000,
        type: 'credit',
        status: 'Completed',
        account: 'High-Yield Savings',
      },
      {
        id: 'TXN-902',
        date: 'Yesterday, 19:40',
        description: 'Four Seasons Resort Maui Reservation',
        merchant: 'Four Seasons Hotels',
        category: 'Merchant Payment',
        amount: 4320,
        type: 'debit',
        status: 'Completed',
        account: 'Visa Infinite (8841)',
      },
      {
        id: 'TXN-903',
        date: 'Sep 05, 2026',
        description: 'Sequoia Growth Capital Fund Call #4',
        merchant: 'Sequoia Capital',
        category: 'Securities',
        amount: 50000,
        type: 'debit',
        status: 'Completed',
        account: 'Investment Portfolio',
      },
      {
        id: 'TXN-904',
        date: 'Sep 02, 2026',
        description: 'Treasury Bill Maturity & Yield Credit',
        merchant: 'US Treasury Bureau',
        category: 'Wire Transfer',
        amount: 25400,
        type: 'credit',
        status: 'Completed',
        account: 'Checking',
      }
    ],
    touchpoints: [
      {
        id: 'TP-1',
        date: 'Sep 07, 2026 - 11:30 AM',
        channel: 'Relationship Manager',
        summary: 'Annual Wealth Planning review conducted with Victoria Sterling. Client discussed secondary venture syndicate allocations.',
        officer: 'Victoria Sterling',
        badgeType: 'success',
      },
      {
        id: 'TP-2',
        date: 'Aug 24, 2026 - 03:15 PM',
        channel: 'Compliance Review',
        summary: 'Periodic AML tier re-certification completed automatically. Zero adverse media alerts detected.',
        officer: 'Automated AML Core',
        badgeType: 'info',
      },
      {
        id: 'TP-3',
        date: 'Jul 12, 2026 - 09:05 AM',
        channel: 'Mobile Banking',
        summary: 'Requested Visa Infinite credit limit expansion from $75k to $100k; approved instantaneously via automated underwriting.',
        officer: 'Credit Risk Engine',
        badgeType: 'action',
      }
    ],
    aiNotes: [
      'Top 1% profitability customer across Northern California private banking cohort.',
      'Anticipated liquidity event in Q4 2026 due to pending strategic venture merger.',
      'High preference for structured treasury notes over standard fixed deposits.'
    ]
  },
  'IND-9022': {
    relationshipScore: 92,
    churnRisk: 'Low',
    lifetimeValue: 98000,
    tenureYears: 4.1,
    accounts: [
      {
        id: 'ACC-802-1049',
        accountNumber: '•••• 1049',
        type: 'Checking',
        balance: 140000,
        currency: 'GBP',
        status: 'Active',
      },
      {
        id: 'ACC-802-5590',
        accountNumber: '•••• 5590',
        type: 'Investment Portfolio',
        balance: 750000,
        currency: 'GBP',
        status: 'Active',
      }
    ],
    cards: [
      {
        id: 'CRD-201',
        cardNumber: '•••• •••• •••• 9904',
        type: 'Mastercard World Elite',
        cardHolder: 'ALEXANDER WRIGHT',
        expiry: '11/28',
        limit: 75000,
        spent: 8900,
        status: 'Active',
        colorGradient: 'from-amber-700 via-orange-800 to-stone-900',
      }
    ],
    transactions: [
      {
        id: 'TXN-911',
        date: 'Today, 11:05',
        description: 'Mayfair Asset Partners Monthly Advisory Fee',
        merchant: 'Mayfair Capital',
        category: 'Fee',
        amount: 1250,
        type: 'debit',
        status: 'Completed',
        account: 'Checking',
      },
      {
        id: 'TXN-912',
        date: 'Sep 06, 2026',
        description: 'LSE FTSE 100 Index Option Settlement',
        merchant: 'London Stock Exchange',
        category: 'Securities',
        amount: 32000,
        type: 'credit',
        status: 'Completed',
        account: 'Investment Portfolio',
      }
    ],
    touchpoints: [
      {
        id: 'TP-21',
        date: 'Aug 30, 2026 - 02:00 PM',
        channel: 'Branch Office',
        summary: 'In-person meeting at Canary Wharf Branch regarding foreign exchange hedging strategies for GBP/EUR exposure.',
        officer: 'Julian Thorne',
        badgeType: 'success',
      }
    ],
    aiNotes: [
      'Frequent cross-currency hedging operations between London and Frankfurt desks.',
      'Recommended candidate for Nexus Global Treasury VIP program.'
    ]
  }
};

export function getCustomer360(individual: Individual): Customer360Profile {
  const existing = MOCK_CUSTOMER_360_DATA[individual.id];
  if (existing) {
    return {
      individual,
      ...existing,
    };
  }

  // Generate sensible dynamic 360 profile for any other or newly inserted individual
  return {
    individual,
    relationshipScore: Math.min(99, Math.max(50, Math.floor(individual.creditScore / 8.5))),
    churnRisk: individual.riskRating === 'high' ? 'Elevated' : individual.riskRating === 'moderate' ? 'Medium' : 'Low',
    lifetimeValue: Math.round(individual.annualIncome * 0.22),
    tenureYears: 2.5,
    accounts: [
      {
        id: `ACC-GEN-${individual.id}-1`,
        accountNumber: `•••• ${individual.id.slice(-4)}`,
        type: 'Checking',
        balance: Math.round(individual.totalDeposits * 0.4),
        currency: 'USD',
        status: 'Active',
      },
      {
        id: `ACC-GEN-${individual.id}-2`,
        accountNumber: `•••• ${Math.floor(1000 + Math.random() * 9000)}`,
        type: 'High-Yield Savings',
        balance: Math.round(individual.totalDeposits * 0.6),
        currency: 'USD',
        status: 'Active',
        interestRate: '4.75% APY',
      }
    ],
    cards: [
      {
        id: `CRD-GEN-${individual.id}`,
        cardNumber: `•••• •••• •••• ${Math.floor(1000 + Math.random() * 9000)}`,
        type: individual.netWorth > 1000000 ? 'Visa Infinite' : 'Nexus Platinum',
        cardHolder: `${individual.firstName.toUpperCase()} ${individual.lastName.toUpperCase()}`,
        expiry: '08/30',
        limit: Math.round(individual.annualIncome * 0.15),
        spent: Math.round(individual.annualIncome * 0.02),
        status: individual.kycStatus === 'rejected' ? 'Frozen' : 'Active',
        colorGradient: 'from-blue-600 via-indigo-800 to-slate-900',
      }
    ],
    transactions: [
      {
        id: `TXN-GEN-${individual.id}-1`,
        date: 'Sep 06, 2026',
        description: 'Direct Deposit Payroll Transfer',
        merchant: individual.employer,
        category: 'Payroll',
        amount: Math.round(individual.annualIncome / 26),
        type: 'credit',
        status: 'Completed',
        account: 'Checking',
      },
      {
        id: `TXN-GEN-${individual.id}-2`,
        date: 'Sep 02, 2026',
        description: 'Electronic Settlement Clearance',
        merchant: 'Automated Clearing House',
        category: 'Wire Transfer',
        amount: 1450,
        type: 'debit',
        status: 'Completed',
        account: 'Checking',
      }
    ],
    touchpoints: [
      {
        id: `TP-GEN-${individual.id}-1`,
        date: `${individual.createdAt} - 10:00 AM`,
        channel: 'Branch Office',
        summary: `Account origin initiated at ${individual.branch}. Identity documentation recorded.`,
        officer: individual.relationshipManager,
        badgeType: 'info',
      }
    ],
    aiNotes: [
      `Client profile classified under ${individual.category}.`,
      `Credit assessment: ${individual.creditScore} (${individual.riskRating.toUpperCase()} risk profile).`,
      `Primary branch: ${individual.branch}.`
    ]
  };
}
