import type { Task } from '@/types';

export const INITIAL_TASKS: Task[] = [
  {
    id: 'TASK-001',
    title: 'Follow up on VIP customer KYC renewal',
    description: 'Eleanor Vance\'s VIP membership is expiring soon. Schedule a call to initiate renewal documentation.',
    assignedTo: 'Sopheak Meas',
    assignedRole: 'SR',
    relatedCustomerId: 'IND-9021',
    relatedCustomerName: 'Eleanor Vance',
    priority: 'High',
    status: 'Open',
    category: 'KYC Review',
    dueDate: '2026-10-05',
    createdAt: '2026-09-25T09:00:00Z',
  },
  {
    id: 'TASK-002',
    title: 'Notify IPO subscribers — PPSP allotment',
    description: 'Send allotment notification letters to all customers who subscribed to PPSP IPO. Coordinate with back-office.',
    assignedTo: 'Dara Heng',
    assignedRole: 'CSO',
    priority: 'High',
    status: 'In Progress',
    category: 'IPO',
    dueDate: '2026-09-30',
    createdAt: '2026-09-22T08:30:00Z',
  },
  {
    id: 'TASK-003',
    title: 'AML periodic review — Q3 High Risk accounts',
    description: 'Conduct AML periodic review for all High Risk rated customers. Document findings and escalate if needed.',
    assignedTo: 'Rattanak Pov',
    assignedRole: 'Manager',
    priority: 'High',
    status: 'Open',
    category: 'Compliance',
    dueDate: '2026-10-15',
    createdAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'TASK-004',
    title: 'Collect ID renewal from Marcus Chen',
    description: 'Customer\'s passport expires in 45 days. Must collect renewed passport copy before expiry.',
    assignedTo: 'Sopheak Meas',
    assignedRole: 'SR',
    relatedCustomerId: 'IND-9022',
    relatedCustomerName: 'Marcus Chen',
    priority: 'Medium',
    status: 'Open',
    category: 'Customer Follow-up',
    dueDate: '2026-10-10',
    createdAt: '2026-09-24T14:00:00Z',
  },
  {
    id: 'TASK-005',
    title: 'Approve pending registration — 3 new accounts',
    description: 'Three registration requests have been waiting at Manager stage for 5+ business days. Review and approve or request resubmission.',
    assignedTo: 'Rattanak Pov',
    assignedRole: 'Manager',
    priority: 'Medium',
    status: 'Open',
    category: 'Approval',
    dueDate: '2026-09-29',
    createdAt: '2026-09-23T09:00:00Z',
  },
  {
    id: 'TASK-006',
    title: 'Call Wealth client — IPO ACLEDA interest',
    description: 'High Net Worth client expressed interest in ACLEDA Bank upcoming IPO. Arrange advisory meeting.',
    assignedTo: 'Dara Heng',
    assignedRole: 'CSO',
    relatedCustomerId: 'IND-9023',
    relatedCustomerName: 'Isabelle Fontaine',
    priority: 'Medium',
    status: 'In Progress',
    category: 'IPO',
    dueDate: '2026-10-02',
    createdAt: '2026-09-26T11:00:00Z',
  },
  {
    id: 'TASK-007',
    title: 'Update trading SR assignment — Q4 rotation',
    description: 'Reassign SR allocations for 8 retail customers as part of Q4 portfolio rotation.',
    assignedTo: 'Rattanak Pov',
    assignedRole: 'Manager',
    priority: 'Low',
    status: 'Open',
    category: 'Other',
    dueDate: '2026-10-31',
    createdAt: '2026-09-27T08:00:00Z',
  },
  {
    id: 'TASK-008',
    title: 'PEP declaration form — Corporate Officer',
    description: 'Collect signed PEP self-declaration form from corporate officer account holder.',
    assignedTo: 'Sopheak Meas',
    assignedRole: 'SR',
    priority: 'High',
    status: 'Open',
    category: 'Compliance',
    dueDate: '2026-10-01',
    createdAt: '2026-09-26T15:00:00Z',
  },
  {
    id: 'TASK-009',
    title: 'Close account documentation review',
    description: 'Customer requested account closure. Ensure all pending settlements are cleared before processing.',
    assignedTo: 'Dara Heng',
    assignedRole: 'CSO',
    priority: 'Medium',
    status: 'Done',
    category: 'Other',
    dueDate: '2026-09-20',
    createdAt: '2026-09-15T09:00:00Z',
    completedAt: '2026-09-19T16:30:00Z',
  },
  {
    id: 'TASK-010',
    title: 'Monthly new account report — September 2026',
    description: 'Compile and submit monthly new account registration report to SECC by end of month.',
    assignedTo: 'Rattanak Pov',
    assignedRole: 'Manager',
    priority: 'Medium',
    status: 'Open',
    category: 'Compliance',
    dueDate: '2026-09-30',
    createdAt: '2026-09-25T08:00:00Z',
  },
];
